### PR TITLE
Add print options onto Shopping List page

### PR DESCRIPTION
**Pull request by lousando**
## Edited: 06/12/2020

**Enhancements:**

- Allows users to change text size of the print table
- Also allows users to hide the list headers

_Note:_ None of the options are saved to localStorage or the database.

**Current Modal Options:**

image

### CODE REVIEW

**Comment by berrnd** [comment]
Thanks.

Have you noticed that there is currently a separate tables used for printing only?
https://github.com/grocy/grocy/blob/59650728a2abf126d703cca355b1f869b06f9ed2/views/shoppinglist.blade.php#L200-L255

Maybe it would be the best thing to create a new page for printing a shopping list with all required options...

I would also prefer to merge #753 before, so a separate page would also make it simpler because of avoiding conflicts...

And I don't know if it's really necessary to introduce Vue for that small part, of course it would be maybe great to use it everywhere, but that would be a rewrite of the frontend in my opinion...

**Comment by lousando** [comment]
Ok, I can move to a separate page 👌

I agree that Vue is a bit overkill for that one feature, but it makes data binding much easier in the front end. If you would like I can also remove it.

**Comment by berrnd** [comment]
> I agree that Vue is a bit overkill for that one feature, but it makes data binding much easier in the front end. If you would like I can also remove it.

From the current added functionality, I see nothing special which can't be handled "natively" in not more or complexer lines of code...

Another idea:
Use the existing table and just apply style changes when using the print dialog, things like sorting or column reordering is already possible since all tables use [DataTables](https://datatables.net/)...
(Can't remember why I have added that second table only for printing and have not done it that way when I've added the printing option...)

**Comment by lousando** [comment]
> Use the existing table and just apply style changes when using the print dialog, things like sorting or column reordering is already possible since all tables use DataTables...
(Can't remember why I have added that second table only for printing and have not done it that way when I've added the printing option...)

I might've been because you get more flexibility from creating a separate container for it 🤷‍♂️

**Comment by lousando** [comment]
>From the current added functionality, I see nothing special which can't be handled "natively" in not more or complexer lines of code...

Performance-wise I will still agree with you that Vue is overkill; we gain almost nothing there. 😞 
I still think developers can still benefit from DOM manipulation even in such a small feature though as it takes an imperative approach to UI building. The benefits of Vue, in this case, are with the `v-model`, `v-if`, and `@click` statements: 🚀 

- `v-model`:  Updates `printTextSize` and allows it to be printed to the screen without manually selecting the DOM node. e.g. `$("#print-text-size").value(printTextSize)`

- `v-if`: Hides/Shows `showPrintHeaders` without manually needing to do `$("#print-staging-area th").hide()`

- `@click`: Binds event handlers once without listener on the parent element and without using inline `onclick`.

**Comment by zsarnett** [comment]
I don't know if moving the Print button makes sense. Especially with the new UI changes.

**Comment by lousando** [comment]
@zsarnett Just got around to looking at the changes; awesome work 👌. I will rebase my branch off of that and re-do my changes.

With the style changes though, the button still only appears when `GROCY_FEATURE_FLAG_SHOPPINGLIST_MULTIPLE_LISTS` is enabled. I think the print button should show even in single list mode, right?

**Comment by zsarnett** [comment]
I do agree with that. It can be removed from the if statement and left in the header, no?

**Comment by hmronline** [comment]
Hi @lousando, 

Have you had any chance to continue this work ?

I will be glad to test this feature and provide feedback, so please let me know if that helps.

Thanks in advance!
Hernán.-

**Comment by lousando** [comment]
@hmronline Not yet, I think I will have time later this weekend however. I will ping you when I have something 👍

**Comment by lousando** [comment]
@hmronline Online you can go ahead and test it now :)

@berrnd I was having trouble adding this to a new page; my PHP is not very good. _However_, I did remove Vue :)

@zsarnett This now builds off of your new style changes :rocket:

**Comment by berrnd** [comment]
This is now done, see https://github.com/grocy/grocy/issues/740#issuecomment-748536983.

**Pull request closed without merging**
