### PR TITLE
Convert services to singletons and use lazy loading to improve performance

### PR DESCRIPTION
**Pull request by zebardy**
This is a first pass at a pull request for changes to turn all services to singletons and for controllers to lazy load services #448. This is a large change and I expect these changes will need further refining.

### CODE REVIEW

**Comment by berrnd** [comment]
Thank you a lot for your efforts on this!

Just wanted to try it out, haven't looked into the code changes in detail so far - but I cannot get it to work...

When visiting the root route (`/`):
```
Type: Error
Message: Call to undefined method Grocy\Services\BaseService::MigrateDatabase()
File: C:\Users\bb\Workspace\grocy\controllers\SystemController.php
Line: 20
```

When visiting `/stockoverview`:
```
Type: Error
Message: Call to undefined method Grocy\Services\BaseService::IsValidSession()
File: C:\Users\bb\Workspace\grocy\middleware\SessionAuthMiddleware.php
Line: 38
```

And just about the `get<Service>()` functions in all the controllers: Would it make a performance difference if we just add these functions for alle services to `BaseController` to have them available in all controllers without adding them to each single one seperately? Would make it more clearly, I think...

**Comment by zebardy** [comment]
Fixed the bug I had introduced due to refactoring the singleton pattern to the parent class. Testing locally I'm building a docker container and running from there. However loading for javascript assets is broken for me at the moment, I think this is due to a bug in the docker container I'm building not the code. However it is 2am, so I'm leaving this here for now.

Shouldn't have a performance impact moving the lazy loading functions to the parent controller as a refactoring. However that's a code refactor I'm not going to attempt at ~2am.

**Comment by zebardy** [comment]
Hi, 

managed to find some more time (and rig up a drone CI environment). I've synced up to master, resolved all of the merge conflicts and applied the changes to the code that has changed since I opened this pull request. I've also moved all of the `get<Service>()` functions to the base controller. 

I've built an arm64 docker container with this code and tested it on my setup. It looks good to me. Please let me know if there is anything else you would like me to change before this can be merged.

**Comment by berrnd** [comment]
Thank you a lot for your work.

Just did some tests and some things did not work, starting with the login page. But I hopefully already found and fixed them all. I also removed a lot of unrelated files before merging.

But most important: I did not measure it, but grocy feels "snapier" now, especially API calls. And even on a "normal" machine. Great! :)

**Comment by zebardy** [comment]
Hi,

Sorry I missed a few things, and thankyou for fixing them. I eyeballed the code untill it became blury and tested as much as i could think of, but obviously missed a few usecases! Cant believe I missed checking in the data files.

Thankyou for getting this merged and glad you can see some benefit. Would be interesting to see if it leads to reduced resource usage on the demo server under heavy load.

I also started experimenting with using APCu to cash some state and data structures between invocations. However that would add another dependency and not sure if it would give as significant of an impact. Will let you know if it comes to anything.

Thanks for your work!

Aaron

**Comment by berrnd** [comment]
>  Would be interesting to see if it leads to reduced resource usage on the demo server under heavy load.

The grocy demo is not the only thing running on that server (it's a LXC container), so I don't have specific statistics, but I don't see a real difference in the total resource usage so far (red line is when the pre-release demo was updated after this was merged)...

grafik

grafik

**Pull request merged**
