### PR TITLE
convert and ceil to next integer the amount to order for the recipe

### PR DESCRIPTION
**Pull request by viktor-c**
This PR means to address this cosmetic issue #2091
Now instead of showing 4,2 bottles of Milk, it will show 5 bottles in the shopping list.

### CODE REVIEW

**Comment by viktor-c** [comment]
I see there will be a problem for meat for example:
Should buy 1,1 kg meat, this will put 2 kg on the shopping list.
There are some quantity units which cannot be divided (e.g. bottles) and ones that should be left fractional. 
What do you think would be a better place to introduce an option to specify this: 
  - when defining quantity units, have a boolean option: fractional
or 
  - as a property of the product: disable rounding in shopping list
when checked it will allow buying a fraction of this unit and disable ceiling in the shopping list

**Comment by berrnd** [comment]
This doesn't address a cosmetic issue, this completely ignores / removes fractional amounts when adding missing ingredients to a shopping list. Maybe it fits you, but this can never be called a solution for the underlying problem / feature request. A _cosmetic_ thing would be doing that only for the UI (which is already possible by utilizing [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) if you want that).

**Comment by viktor-c** [comment]
> A _cosmetic_ thing would be doing that only for the UI (which is already possible by utilizing [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) if you want that).
Is an UI only solution of displaying the amount as above worth looking into or is it doomed to be rejected?

**Comment by berrnd** [comment]
> Is an UI only solution of displaying the amount as above worth looking into or is it doomed to be rejected?

Nothing was ever and will ever be rejected when it generally works and doesn't only cover one (your) specific use case. This here was rejected because it removes information (fractional amounts), as already pointed out above.

**Comment by viktor-c** [comment]
> > Is an UI only solution of displaying the amount as above worth looking into or is it doomed to be rejected?
> 
> Nothing was ever and will ever be rejected when it generally works and doesn't only cover one (your) specific use case. This here was rejected because it removes information (fractional amounts), as already pointed out above.

I see in your mentioned issues a lot of CustomJs code. Maybe somehow off topic, can you put together a set of "snippets" which could then be activated from the UI. Say you have one for ceiling amount in the shopping list, you have one to enable a checkbox as default and so on, like gathering some of the useful ones. By describing this in the _Readme.md_ maybe you can avoid so many opened issue.

**Comment by berrnd** [comment]
> can you put together a set of "snippets" which could then be activated from the UI

Of course I technically could, but if one can't open a text file and copy & pasting a snippet found somewhere, than custom JS is not what one needs. Beside that, custom JS is _custom_ - it will never be used for a built-in solution. But of course, like for just like anything related to UI, JS is most likely needed for that - but there is not only custom JS in Grocy, but also built-in JS ([ref1](https://github.com/grocy/grocy/tree/master/public/js), [ref2](https://github.com/grocy/grocy/tree/master/public/viewjs)).

&nbsp;
> By describing this in the Readme.md maybe you can avoid so many opened issue.

Yes, I also thought one time that a README prevents the same over and over again (frustrating) reports. Life thought me something different, especially in 2023 - too many people are unable to read READMEs in reality.

**Pull request closed without merging**
