### PR TITLE
Add reference to PikaPods service

### PR DESCRIPTION
**Pull request by m3nu**
Hi there,

Over at [PikaPods.com](https://www.pikapods.com/), we are on a mission to make great open source apps, like Grocy more accessible and simpler to get started with. Since many of our users have [requested](https://feedback.pikapods.com/posts/126/add-app-grocy) the app, it's now available for simple 1-click deployment.

Hope this helps more people find and use the app. We also featured it in our newsletter this  month.

This PR would also add a reference to PikaPods, as additional install option for people who want to use the web app, but don't manage their own server. This would help an even wider audience to benefit from the project.

We are also big on open source sustainability and offer a revenue share with authors to support continued development. We can discuss this in a few weeks, once we have a better idea of the user numbers.

Looking forward to hearing the team’s opinion on this. Thanks for the consideration!

Manu, founder

### CODE REVIEW

**Comment by berrnd** [comment]
Thanks, but that's the wrong place.

The more appropriate place would be the [website](https://grocy.info/) ([repo](https://github.com/grocy/grocy-website)), where all other community contributed tools/integrations are listed - feel free to add it there.

&nbsp;
> revenue share with authors to support continued development

Also thanks for that, but I'm not interested - Grocy isn't driven by money, more (only) by time and desire (it's a hobby, not a business, now and forever).

**Comment by m3nu** [comment]
Makes sense. Will check over there later.

**Comment by berrnd** [comment]
So far, all other community contributed apps/tools/integrations (listed on the website) are Open Source hobby projects in the same way as Grocy itself.

So this would be the first commercial (Closed Source, related to the provided infrastructure / hosting) offering around Grocy. Needs some consideration if I want that generally on the website, spontaneously I would say no, but haven't thought it to the end yet.

**Comment by berrnd** [comment]
> Needs some consideration if I want that generally on the website

That you don't need to waste time on a PR at [grocy-website](https://github.com/grocy/grocy-website) - I made the following decision on that topic:

No commercial or Closed Source app/tool/integration for Grocy will ever be linked on any official channel (as of now: the website, any repo in the _grocy_ organization here, the r/grocy subreddit and the _grocy_erp_ Twitter handle).

**Pull request closed without merging**
