### PR TITLE
Improve Performance

### PR DESCRIPTION
**Pull request by fipwmaqzufheoxq92ebc**
Hi,

I tried to improve the Performance of the "Stock overview" page, and found some improvements:
1) I replaced some of the `FindObjectInArrayByPropertyValue`-calls by getting this values directly in the database query.
This also made the template-code more readable.

2) I optimized the "stock_current"-database-view:
I created 2 indices, and replaced a subquery with a (left-)join.
I'm not sure why, but this combination improved the speed significantly.
stock_current is used often:
I got a speedup from 1.26s to 0.13s on /stock/products #848
The view stock_missing_products, which uses stock_current, is now 25 times faster (from ~1250 ms to ~50ms) on my sample data.

Might be related to #898 (Note that JavaScript ("Datatables") also has some loading time. I think pagination could fix that.)

### CODE REVIEW

**Comment by berrnd** [comment]
Great, thanks a lot for that too! :)

Makes sense to have the columns needed for the stock overview table populated by a SQL query - just one thing:
I tried to avoid to have "bigger" SQL queries in-code.
So maybe a view instead of the query in `GetCurrentStockOverview()` would be great, if possible somehow with the dynamic JOIN part based on feature flags...

> Note that JavaScript ("Datatables") also has some loading time. I think pagination could fix that.

The only real enhancement would be to have pagination + load the data dynamically and not render the whole HTML table server side...
The biggest table the stock journal, I have about 10K lines there on my private instances which loads currently in about 10 seconds - great that this page is only needed rarely on daily grocy use cases... :D

**Comment by fipwmaqzufheoxq92ebc** [comment]
> Makes sense to have the columns needed for the stock overview table populated by a SQL query - just one thing:
> I tried to avoid to have "bigger" SQL queries in-code.
> So maybe a view instead of the query in `GetCurrentStockOverview()` would be great, if possible somehow with the dynamic JOIN part based on feature flags...

I changed that: I create now two views and query them.

**Comment by berrnd** [comment]
Thanks again - the page speed improvement on the stock overview page is noticeable. :)

Maybe we should extend this "helper-view-approach" to at least all other overview pages...

**Comment by berrnd** [comment]
I have no explanation, but any of the indexes create in [that migration](https://github.com/grocy/grocy/blob/62e8d88adb321d916a1a61eccb4efaf081f7f354/migrations/0106.sql) made that the `stock_current` view failed (the `is_aggregated_amount` did not work anymore, returned always `0`).

I searched for over an hour, but haven't found out what specific thing the problem is, it seems to be the combination of those indexes - strange...

**Pull request merged**
