### PR TITLE
Add support for transitive unit conversions

### PR DESCRIPTION
**Pull request by esclear**
As discussed in #2039, here's a WIP pull request that adds support for transitive unit conversions to grocy.

When using it, I noticed that floating point inaccuracies may arise.
E.g. referring to the conversions defined in #2039, instead of `2 TL`, the UI will ` 1.9999 TL`.
However, this likely would have happened for a single conversion as well, depending on the factors, as the recipe ingredients are stored internally in the storage unit (?).

Regarding the query, I tried to keep the original one mostly the same and put it in the `single` CTE.
However, I removed the joins with the `quantity_units` table, as those were only used for the names and not relevant for the calculations, and moved them to the final `SELECT`.

When writing this, I thought that the `source` column mostly serves as a kind of debugging help.
I am inclined to remove the `source` column from the final result and possibly also remove it completely, if that's okay for you.
From the query in https://github.com/grocy/grocy/issues/2039#issuecomment-1336116371 I gathered, that this may be used for some sort of disambiguation of conversions, but this could be used to the `closure` CTE (and then the `LIMIT` would not be necessary anymore).

### CODE REVIEW

**Comment by berrnd** [comment]
Thanks a lot!

Haven't looked at it technically so far, just gave it a quick try - demo instance (your added migration is manually applied there): https://test-3z8g2vbc6tp9uko4btp2jo.demo-prerelease.grocy.info

The only existing product there has mixed conversions for testing different cases of "conversion paths":
- Base / QU stock = Bottle
  - 1 Liter = 1 Bottles (Product override conversion)
  - 1 Pack = 6 Bottles (Product override conversion)
  - 1 Liter = 1000 Milliliters (Default conversion)
  - 1 Pack = 2 2xPacks (Default conversion)

Adding:
- 1 Bottle => shows 1 Bottle => correct 🟢
- 1 Liter => shows 0.167 Bottles => not correct (should be 1 Bottle) 🔴
- 1000 Milliliters => show 0.167 Bottles => not correct (should be 1 Bottle) 🔴
- 1 2xPacks => shows 2 Bottles => not correct (should be 12 Bottles) 🔴
- 1 Pack => shows 6 Bottles => correct 🟢

So based on that less cases work than before.

Looking at the output of `quantity_unit_conversions_resolved` directly it looks better (from what I can see at a first glance), so maybe it's "just" about the frontend.

Here is the database file of the above linked demo instance if you want to fiddle there:
[grocy.db.zip](https://github.com/grocy/grocy/files/10146867/grocy.db.zip)

In the in #1360 referenced duplicate issues a lot of other practical examples are mentioned, a couple of them should be used to verify that it works.

**Comment by berrnd** [comment]
Would be great if you can add a little explanation about how you solved it / it works (for example what the idea about the CTEs `single`, `closure`, `closure_rn` is / what they represent).

&nbsp;
> E.g. referring to the conversions defined in #2039, instead of `2 TL`, the UI will ` 1.9999 TL`.
> However, this likely would have happened for a single conversion as well, depending on the factors, as the recipe ingredients are stored internally in the storage unit (?).

Yes, all amount and money values stored anywhere are related to the products stock QU. This can't be solved generally unless not using decimals (ref #389). If you store the values related to the destination QU (so for example for the QU used in the recipe ingredient), you just have the problem in the other direction (so proper display on the recipe ingredient, but having the rounding issue when doing the stock fulfillment check / consume transaction).

&nbsp;
> When writing this, I thought that the `source` column mostly serves as a kind of debugging help.

That's currently not only used for debugging, but also to make the hierarchy work. Product specific overrides of a maybe existent same default conversion should override it. The view is ordered by that column and the consumer should do a SELECT as mentioned in https://github.com/grocy/grocy/issues/2039#issuecomment-1336116371 to get the right factor for a specific conversion (maybe that's also a problem of the current state / why it doesn't work for the frontend).

**Comment by esclear** [comment]
> Would be great if you can add a little explanation about how you solved it / it works (for example what the idea about the CTEs `single`, `closure`, `closure_rn` is / what they represent).

Sure, I'll do that.

> That's currently not only used for debugging, but also to make the hierarchy work. Product specific overrides of a maybe existent same default conversion should override it. The view is ordered by that column and the consumer should do a SELECT as mentioned in [#2039 (comment)](https://github.com/grocy/grocy/issues/2039#issuecomment-1336116371) to get the right factor for a specific conversion (maybe that's also a problem of the current state / why it doesn't work for the frontend).

The query / view, as I have written it, does not contain any duplicate conversion.
That is, for every triple (product, start quantity, end quantity), there is exactly one row and therefor one factor.

Regarding the examples you have given in https://github.com/grocy/grocy/pull/2056#issuecomment-1336190121, I was wondering, how the conversion factor for the conversion `1000 Milliliters => show 0.167 Bottles` is calculated.
Is it just the inverse of the Bottles → Milliliters conversion factor?

I'm asking that because it seems that the (inverse?) default conversion Milliliters → Liters is not taken into account here for the original query, as otherwise there would be a corresponding row here.

If that's okay for you, I can rewrite the query a bit more, though I'm not quite sure regarding the semantics of the factors yet.

As I gather from the [original query](https://github.com/grocy/grocy/blob/e8f76e5694f2defb69435bccfaeb8de96870322c/migrations/0189.sql), there are four sources for conversions:

1. purchase to stock conversion factors (and their inverses)
2. product specific QU overrides
3. default QU conversions

And for every product, the precedence of these conversions is the order they are listed above, i.e. if there is a purchase to stock conversion, the product specific override is ignored?

Can you elaborate on what the purpose of the 4th variant (default indirect qu conversion) is exactly?

Is there any documentation on the conversions that may exist and their precedences?
I didn't find any, but this would clear this up, I think.

**Comment by berrnd** [comment]
> Can you elaborate on what the purpose of the 4th variant (default indirect qu conversion) is exactly?
> Is there any documentation on the conversions that may exist and their precedences?

It's just "one (and the only -> current limitation) more level", beside directly related conversions. So for my example above, that is the `Milliliters <-> 2xPacks` conversion. Most probably that's not longer needed when having your / a generic approach to resolve conversion indefinitely.

There is no documentation about anything, beside some code comments or what's discussed here and on [reddit](https://www.reddit.com/r/grocy/). If something is unclear, just ask, I'm happy to answer anything.

&nbsp;
> Regarding the examples you have given in https://github.com/grocy/grocy/pull/2056#issuecomment-1336190121, I was wondering, how the conversion factor for the conversion `1000 Milliliters => show 0.167 Bottles` is calculated.

That's the output of `quantity_unit_conversions_resolved` for my example product above:

grafik

The `productamountpicker` component consumes that [here](https://github.com/grocy/grocy/blob/3b3212d101f74d180af50c7c4dbc08adc2d9bac4/public/viewjs/components/productamountpicker.js#L14-L26) (in the order of the view, so `ORDER BY source`), but only the first per `to_qu_id`. That means the above yellow highlighted conversion is picked for that example (1000 / 6000 = 0,1666666666666667).

There was currently no need to filter on `from_qu_id` there (since there was no unlimited hierarchy). It's of course also ok to change that part, maybe this is all to pick the `Bottle<->Milliliters` conversion (untested):
https://github.com/grocy/grocy/blob/3b3212d101f74d180af50c7c4dbc08adc2d9bac4/public/viewjs/components/productamountpicker.js#L22

Changing this line to (picking only factors where `from_qu_id` = the products stock QU):
```js
if (!$('#qu_id option[value="' + conversion.to_qu_id + '"]').length && conversion.from_qu_id == destinationQuId)
```

&nbsp;
> Does the query need to return a factor of `1.0` for products where the purchase unit matches the stock unit?

Currently not needed because of:
https://github.com/grocy/grocy/blob/3b3212d101f74d180af50c7c4dbc08adc2d9bac4/public/viewjs/components/productamountpicker.js#L17-L20

**Comment by berrnd** [comment]
About the products `Factor purchase to stock quantity unit`:

That only exists due to historic reasons, it was was once the only factor / conversion before the generic conversion handling was added in [v2.5.0](https://grocy.info/changelog#v2.5.0)).

I'm also open to and already thought of removing it. So migrating that factor (when not `1`) to a product specific conversion + removing that field. Maybe that would make this here easier.

**Comment by esclear** [comment]
Okay, I decided to rewrite the view from the ground up and added some comments.
If there's anything unclear with the query, just ask.

I have tested it with the following setup that should, I think, cover all possibilities:
* Five units `A`, `B`, `C`, `D`, `E`
* Just one product (id = 1)
* The following conversions:
  * Default conversion A → B with a factor of 2
  * Purchase→Stock conversion B → C with a factor of 3
  * Default conversion B → C with a factor of 11
  * Product-specific conversion C → D with a factor of 5
  * Default conversion D → E with a factor of 7

As a "graphic":
```
Unit  Factor  Type
A
↓        2    Default conversion
B
↓        3    Purchase → Stock conversion
C
|      (11)   Default conversion (shall NOT be used)
↓        5    Product-specific conversion
D
↓       7    Default conversion
E
```

So in the end the result should consist of 20 conversions (with 20 distinct values), namely those, where the start and end units are different.
In particular, there should be a conversion from A to E with a factor of 2*3*5*7 = 210 and an inverse one from E to A with a factor of ~ 0.00476.

And indeed, the result looks as follows:

|id|product_id|from_qu_id|from_qu_name|from_qu_name_plural|to_qu_id|to_qu_name|to_qu_name_plural|factor|source|
|--|--|--|--|--|--|--|--|--|--|
|-1|1|1|A|As|2|B|Bs|2.0|/1/2/|
|-1|1|1|A|As|3|C|Cs|6.0|/1/2/3/|
|-1|1|1|A|As|4|D|Ds|30.0|/1/2/3/4/|
|-1|1|1|A|As|5|E|Es|210.0|/1/2/3/4/5/|
|-1|1|2|B|Bs|1|A|As|0.5|/2/1/|
|-1|1|2|B|Bs|3|C|Cs|3.0|/2/3/|
|-1|1|2|B|Bs|4|D|Ds|15.0|/2/3/4/|
|-1|1|2|B|Bs|5|E|Es|105.0|/2/3/4/5/|
|-1|1|3|C|Cs|1|A|As|0.166666666666667|/3/2/1/|
|-1|1|3|C|Cs|2|B|Bs|0.333333333333333|/3/2/|
|-1|1|3|C|Cs|4|D|Ds|5.0|/3/4/|
|-1|1|3|C|Cs|5|E|Es|35.0|/3/4/5/|
|-1|1|4|D|Ds|1|A|As|0.0333333333333333|/4/3/2/1/|
|-1|1|4|D|Ds|2|B|Bs|0.0666666666666667|/4/3/2/|
|-1|1|4|D|Ds|3|C|Cs|0.2|/4/3/|
|-1|1|4|D|Ds|5|E|Es|7.0|/4/5/|
|-1|1|5|E|Es|1|A|As|0.00476190476190476|/5/4/3/2/1/|
|-1|1|5|E|Es|2|B|Bs|0.00952380952380952|/5/4/3/2/|
|-1|1|5|E|Es|3|C|Cs|0.0285714285714286|/5/4/3/|
|-1|1|5|E|Es|4|D|Ds|0.142857142857143|/5/4/|

I have also added the database used for these tests here: [grocy.db.zip](https://github.com/grocy/grocy/files/10147504/grocy.db.zip)

**Comment by berrnd** [comment]
Thanks again a lot for your work!

The view-output looks good and I also like and it's understandable how you structured it - thanks for adding the comments. 👍

I have applied the updated view on the [demo instance from yesterday](https://test-3z8g2vbc6tp9uko4btp2jo.demo-prerelease.grocy.info) and the "UI problems" are the same there - I will have a look at that later. Most likely not a big thing, as also mentioned above.

I also faced this:
On my dev machine I'm currently using SQLite 3.33.0 and there the view produced this error:
```
SQLSTATE[HY000]: General error: 1 circular reference: closure
```

It's no problem on the demo server, which is currently using SQLite 3.34.1.

Turns out that it's this enhancement of [SQLite 3.34.0](https://sqlite.org/releaselog/3_34_0.html):
> Enhance [recursive common table expressions](https://sqlite.org/lang_with.html#recursivecte) to support two or more recursive terms as is done by SQL Server, since this helps make [queries against graphs](https://sqlite.org/lang_with.html#rcex3) easier to write and faster to execute.

I guess you use SQLite >= 3.34.0?

So we need to raise the required SQLite version (I have no problem with that).
Probably makes sense to also finally raise the PHP requirement to 8.1 (there are breaking changes which affect grocy, so something to do there) and to also do "remove the products qu-purchase-to-stock-factor", to have all breaking changes in one release (means grocy 4.0).

**Review by berrnd — APPROVED** [review]
The view looks good and works, thanks again - required changes for the frontend to properly pick the conversion factors will be done outside of this pull request.

**Comment by berrnd** [comment]
The required changes to make this work for the frontend are done and the pre-release demos are updated, if you want to try it.

From what I can tell, your original example in https://github.com/grocy/grocy/issues/2039#issue-1447104244 now also works as expected: https://test-n4a1oa5u94vqeaehk7ot.demo-prerelease.grocy.info/recipe/7

**Comment by esclear** [comment]
Great, thanks a lot.

> I guess you use SQLite >= 3.34.0?#
Yes, I'm on 3.39.4

The query could technically be rewritten to work with versions older than 3.34.0, however it would not be nearly as readable.
And considering that SQLITE 3.34 is two years old at this point, I think it is fair to use this as a minimal requirement.

Today it occurred to me that there is a small problem with the query in this PR, regarding products to which only default conversions apply.
However the fix is easy and I'll open another PR for it.

**Comment by berrnd** [comment]
There seem to be performance issues when having a couple of more products which need to be resolved before releasing that - see https://github.com/grocy/grocy/issues/2081#issuecomment-1364539612 (an example database is attached there in the first comment).

> About 550 products, no global QU conversions, no product specific conversion, so only "Factor purchase to stock quantity unit"-based conversions.
> 
> Querying `quantity_unit_conversions_resolved` for a single product takes about 7 seconds, of course not so fast and this needs to be improved before releasing the new QU conversion handling.
> 
> ```
> Ausführung wurde ohne Fehler beendet.
> Ergebnis: 3 Zeilen in 6927ms zurückgegeben
> In Zeile 1:
> SELECT *
> FROM quantity_unit_conversions_resolved
> WHERE product_id = 3
> ```

**Comment by esclear** [comment]
Oh yeah, that's a problem.
I didn't experience any problems myself, though I only have way less products.

I'll have a look at the database provided in #2081.

A first thought would be to materialize the view in some way, though that's not possible with SQLITE.

However, this should only be a last resort and I'm honestly surprised that the query is so slow.

**Comment by esclear** [comment]
My first observation is that for me it doesn't take nearly as long, just about 0.5 seconds.
```
λ time sqlite3 grocy.db 'SELECT * FROM quantity_unit_conversions_resolved WHERE product_id = 3;'
-1|3|3|Packung|Packungen|4|Gramm (g)|Gramm (g)|16.0|/3/4/
-1|3|4|Gramm (g)|Gramm (g)|3|Packung|Packungen|0.0625|/4/3/
-1|3|4|Gramm (g)|Gramm (g)|4|Gramm (g)|Gramm (g)|1.0|/4/4/

________________________________________________________
Executed in  505.29 millis    fish           external
   usr time  504.24 millis  259.00 micros  503.98 millis
   sys time    1.07 millis   68.00 micros    1.00 millis
```

That is still way too long for my taste, but – considering that the device I tested the query on is not that powerful – makes me suspect that there may be more to it.
I'm thus wondering with version of sqlite you used to test this, @CommanderRoot, @berrnd.
I'm currently on 3.39.4.

**Comment by berrnd** [comment]
Thanks for having such a quick look.

I use SQLite 3.34.1 on my development machine and on the demo server and 3.35.5 when working with [DB Browser for SQLite](https://sqlitebrowser.org/) (guess it was bundled with that).

Did a quick test with the latest 3.40.0 SQLite release, and yeah - it's faster there.

But making SQLite >= 3.39.4 a requirement would be a big step...

**Comment by esclear** [comment]
Okay, so reading the changelog may give some hints as to what changed and where the improvements stem from.
For now I'll have a look at the query plans and maybe find some info there.

**Comment by esclear** [comment]
A quick look confirmed my suspicion that the bottle neck is related to the default conversions that are only added when they are "reached" by product units.

I'll have a closer look at this when the festive social obligations are done.
Cheers! 🎄

**Comment by berrnd** [comment]
Thanks again and absolutely no need for a hurry - the next release is still kind of far away mostly due to things related to the PHP 8.1 upgrade.

And if the `Factor purchase to stock quantity unit` is the cause for the problems, maybe let's finally remove that (as [mentioned above](https://github.com/grocy/grocy/pull/2056#issuecomment-1336208338)).

But now it's christmas things - have a beautiful time.

**Comment by esclear** [comment]
My suspicion proved correct, on my machine the query time got down from ~1800 ms to ~40 ms for the database provided in #2081.
The reason was that sqlite produced rather inefficient query plans (doing a full table scan for the joins) and by rewriting the query a bit, we can give it enough hints to prevent that.

There's some "quality control" left that I'd like to do, including comparing the query plans with older, i.e. >= 3.34, versions of sqlite.

Although that isn't needed, I think we could still replace the purchase to stock factor as mentioned before.
I think the main improvement would be that the whole conversion affair becomes easier to think about – I have to admit the factor confused me in the beginning.
Also, I suppose that this would make the code simpler elsewhere – the query wouldn't be affected much.

By the way, I noticed that there are two migrations for the transitive conversions, `0203.sql`, the one from this PR and `0204.sql` that are almost identical (safe for a column name and some formatting changes).
Is that on purpose? Would it be sensible to coalesce these again?
Or should I put the view with the improvements in a new migration?

**Comment by berrnd** [comment]
> Is that on purpose? Would it be sensible to coalesce these again?
> Or should I put the view with the improvements in a new migration?

Migrations are only supposed to work between releases, so an existing unreleased migration about the same view could be changed. However sometimes I decide to create a new migration file, even for small changes - in this case there were other issues related to QU conversions reported and reproduced on pre-release demo instances - existing demo instances wouldn't catch up changed migrations, that was the only reason there.

**Comment by berrnd** [comment]
I've removed the products `qu_factor_purchase_to_stock` (migrating existing factors to normal product specific QU conversions) in 0229d187aedfe50446ad42887810e70ba0b86109.

**Comment by esclear** [comment]
Okay, I finished my tests with older sqlite versions.
The query plan look all sensible.
I did a very unscientific benchmark on the database from #2081 that yielded the following times:

|sqlite version|query duration as of 15f7ac3da02556a74e1d80e7d090af63faa1ba5b |duration with improvements|
|---|---:|---:|
|3.34.1|1040 ms| 84 ms|
|3.35.5| 719 ms| 82 ms|
|3.36.0| 702 ms| 83 ms|
|3.37.0| 673 ms| 84 ms|
|3.38.5|520 ms| 56 ms|
|3.39.4|528 ms|16 ms|

That factor ~12 reduction on 3.34.1 is a win in my book, though I wish that more improvement was possible.
Furthermore, although it is not needed per se, I would personally lean to _recommending_ sqlite >= 3.38 or even >= 3.39 for the (stressing this again: anecdotal) speed gains I observed.

I'm currently preparing a PR with the proposed change to the view.

**Comment by berrnd** [comment]
Thanks again for your time you put into this - looks good from the tests I would say.

&nbsp;
> I would personally lean to recommending sqlite >= 3.38 or even >= 3.39 for the (stressing this again: anecdotal) speed gains I observed.

For me requiring current runtime stuff (which most of the times runs faster) would be no problem, however, there will be (as it was always the case when raising requirements) a kind of shitstorm when doing that. People run grocy on shared hosting which tend to use ancient runtime stuff just like always, for whatever reason. And e.g. the current PHP(-FPM) 8.1 package (at least on Debian) seems to bundle SQLite 3.34.1 - so I would prefer to leave it at that for now, but we can of course add a note on the changelog and/or README that a newer SQLite version is better for performance.

**Pull request merged**
