### PR TITLE
Refactor Authentication and add proxy-authentication

### LINKED ISSUE #627: Feature Request: Use username from reverse proxy
Hello,

I want to use grocy behind a reverse nginx proxy, similar to other services that I use. For my other services, I also use the nginx PAM module for authentication to keep the password management for all services in one place.

It would be great if grocy would be able to use the username supplied in a request header.
This request seems related to #246 , but instead of using the first user in the database, it would probably need to create users if they do not exist.

### PR DESCRIPTION
**Pull request by fipwmaqzufheoxq92ebc**
Hi,
I refactored the Authentication-System:
I created a new abstract class AuthMiddleware which does common tasks (e.g. check if auth is disabled or in demo-mode).
Currently, there are four Subclasses:
Session-, ApiKey- and Proxy-, DefaultAuth- Middleware

DefaultAuth checks for an Api-Key or Session.	
Note: The old implementation used Session for UI and Api-Key or Session for the API. Now, there is only one setting for both, so you can access both with Api-Key or Session. I don't think that's a problem.

The Proxy-Authentication uses the username from the reverse Proxy.
e.g. for nginx:
`fastcgi_param  HTTP_X_USERNAME <username>;`
where <username> is the username to use.

A new Setting 'AUTH_CLASS' configures which Middleware to use.
DefaultAuthMiddleware is the default.

When Proxy-Auth is used, I hide the "Logout", "Change password" and "Manage users" buttons.

Fixes #627   (and #828)
Also might help for #305, #207

### CODE REVIEW

**Comment by berrnd** [comment]
Cool, thanks a lot! :)

Will review this as soon as possible, but currently I cannot really work on grocy - will hopefully change in the next couple of weeks..

**Review by berrnd — APPROVED** [review]
I did some extensive tests with that, everything basically worked - thanks again. :)

I noted and fixed the following:
- Undefined constant warnings when `MODE` was not `production` or when `DISABLE_AUTH` was set to `true`
- `AuthMiddleware` always redirects to `/login` when unauthenticated, this is ok for frontend routes, but not for the API (which should return a 401 response instead) - I tried to distinguish that by the URL for now in `AuthMiddleware`

**Comment by knnnrd** [comment]
Hi @berrnd, when will you tag a new release containing this PR?
Thanks

**Comment by berrnd** [comment]
I never promise release dates, but see: https://www.reddit.com/r/grocy/comments/jvphp8

**Pull request merged**
