### PR TITLE
Display ingredients and recipe side by side

### PR DESCRIPTION
**Pull request by Dehalion**
This tries to improve PR #1628 by @adamschmalhofer to implement Feature Request #2051

### CODE REVIEW

**Comment by Dehalion** [comment]
This just displays ingredients and recipe steps side by side and hopefully fixes the problems with multi recipies.
For those it would be even nicer to have them stacked from top to bottom instead of hidden by recipe tabs, but the order is in reverse for that and there are not much unique classes. That's also why I resorted to attribute selectors.

**Review by berrnd — CHANGES_REQUESTED** [review]
Standard 1920x1080 resolution:

The ingredients column is IMHO not really that readable when having it so narrow (maybe collapsing the stock fulfillment info into a tooltip or something would be a good approach):

grafik

Even more a problem on smaller screens - tested by the common 1366x786 resolution:

grafik

For multi-/nested recipes and the rest definitely better. 👍

**Comment by berrnd** [comment]
Technical side note: Since those CSS styles are only required for the /recipes page, it better fits into that view than in the global grocy.css file - so here:

https://github.com/grocy/grocy/blob/2ebb9b2cd91e52e132171ef53fbb63fcb0373da2/views/recipes.blade.php#L8-L13

**Comment by Dehalion** [comment]
> Technical side note: Since those CSS styles are only required for the /recipes page, it better fits into that view than in the global grocy.css file

I was thinking the same, but didn't find any more CSS files. Didn't look into the view files on my own.
I moved it there, but Github Code spaces messed up my branch with merges, I will clean it up and address your concerns with the width of the ingredients column.

What do you mean by "stock fulfillment info"?
And is there a library for nice tooltips and an example location to look at? Or do you mean just adding a `title` attribute?
Would it be a problem on mobile platforms to move this info into a tooltip?

**Comment by berrnd** [comment]
> What do you mean by "stock fulfillment info"?

This:
grafik

&nbsp;
> And is there a library for nice tooltips and an example location to look at?

grocy uses Bootstrap (v4) and therefore their tooltips throughout - example:
grafik

Doc ref: https://getbootstrap.com/docs/4.2/components/tooltips

**Comment by berrnd** [comment]
I've finished this now (using another approach) in daf5ad33c7010dea9e8d8c85d5ecc42d7c9a9b3e.

**Pull request closed without merging**
