### PR TITLE
Allow possibility to choose custom homepage

### LINKED ISSUE #294: Redirection to Page Not found when feature deactivated
When clicking the Grocy logo, or when entering just the bare URL, I'm getting redirected to the equipment section as a sort of Start page. This is problematic because I actually deactivated that feature, and therefor getting a Page Not found error. Can the Start page be changed in any way? Any activated feature would be great, selectable would even be better.

### PR DESCRIPTION
**Pull request by nielstholenaar**
Hi.

I wanted to changed the default view to the shopping list instead of the stock overview. After a little bit thinking i thought why not make in configurable. 

This PR introduces a new Setting "GROCY_ENTRY_PAGE" which can be set to any of the available features. (stock,shoppinglist, .......)

This will close #294.

### CODE REVIEW

**Comment by berrnd** [comment]
Great idea, thank you! :)

But I think this would result in an `404` error when you set it for example to `batteries` and set at the same time `Setting('FEATURE_FLAG_BATTERIES', false);` ... so maybe some handling for this would be needed as well...

**Comment by nielstholenaar** [comment]
I'm currently on a small vacation. When I'm back home I will add some checking to prevent any 404

**Comment by nielstholenaar** [comment]
I have made the necessary changes to handle any the disabling of an specific feature.

I also added a fallback to handle the scenario when the requested entry page has been disabled. In that case the about page will be served instead.

**Comment by nielstholenaar** [comment]
I have updated the docblock in the config-dist.php file

**Comment by berrnd** [comment]
Thank you, merged it. :)

**Pull request merged**
