### PR TITLE
Add API call to remove an item from the shopping list by productid

### PR DESCRIPTION
**Pull request by Forceu**
This adds an API call, so a shopping list item can easily be removed

Please note: This is **UNTESTED**, as I was unable to run the current grocy master commit on my server.

### CODE REVIEW

**Comment by berrnd** [comment]
Thank you! :)

Looks good to me at first sight, will review and integrate this soon...

**Comment by Forceu** [comment]
Thanks for the quick reply! Sorry I am new to Github and am trying to make it two seperate PRs, somehow they got merged however.

The second PR is another change to the API as well, where the default best before date is used if no parameter is given for AddProduct().

**Comment by berrnd** [comment]
I've merged this now with some little naming changes - see https://github.com/grocy/grocy/commit/cc1c6a6442cd2c958787950cadc59a83aa4f53cb.

Also when no best before date is supplied and also the given product has no "Default best before days" set, I changed it to still us today - maybe not the best thing, but it behaved like that so far and I don't want a breaking change for that now...

Thanks again. :)

**Comment by Forceu** [comment]
I completely forgot that, yes you are right. Great to see the change merged! :)

**Pull request merged**
