### PR TITLE
StockService: Set the product's bestBeforeDate to the freezer date if it is being purchased to a freezer

### PR DESCRIPTION
**Pull request by grahamc**
Not yet tested, but I'm about to try it!

### CODE REVIEW

**Comment by berrnd** [comment]
Thanks, related to / requested in #1160.

But if, then please also prefill that on the /purchase page (like the `Default due days`) to make this more comprehensible and still be able to change it if needed.

**Comment by grahamc** [comment]
I just pushed a fixup making the "Purchase" flow's date picker default to the freezer's best before date, too. Thanks for the suggestion! I've also checked that this works now.

**Review by berrnd — CHANGES_REQUESTED** [review]
Thanks again, noticed this while testing the changes:
On purchase, the due date is only prefilled when the products default location is a freezer, not when that's not a freezer, but I just put it this time directly into the freezer (so prefilling also needs to take place when changing the location)

**Comment by grahamc** [comment]
That makes sense, I don't know how to implement that, though. Can you offer any pointers or suggestions? I don't do a lot of web development, and the stuff I did here took a lot of experimenting and looking around to figure out. I'm happy to fix this issue but I think I'd need some help.

**Comment by berrnd** [comment]
No problem, thanks again - that's now finalized by the two commits referenced above.

**Review by berrnd — APPROVED** [review]

**Pull request merged**
