### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by bbreton09**
Translation of some missing sentences in French.

### CODE REVIEW

**Comment by berrnd** [comment]
Thank you, but Translations are managed on Transifex, as mentioned in README: https://github.com/grocy/grocy#localization

Please change it there.

**Comment by bbreton09** [comment]
Oups sorry i'm going to see what is Transifex :)

**Comment by bbreton09** [comment]
> Thank you, but Translations are managed on Transifex, as mentioned in README: https://github.com/grocy/grocy#localization
> 
> Please change it there.

why Transifex says 100% for french when for example the file string.po is missing translation? Surely I missed something?

**Comment by berrnd** [comment]
Because it seems to be already done.

I just take one example string `Add recipe on %s`:
Was translated 9 days ago, the last release was 18 days ago, I only pull translations before a release, that's why it's not included in the master branch here yet...

grafik

**Comment by bbreton09** [comment]
> Because it seems to be already done.
> 
> I just take one example string `Add recipe on %s`:
> Was translated 9 days ago, the last release was 18 days ago, I only pull translations before a release, that's why it's not included in the master branch here yet...
> 
> grafik

Ok, thank's to have take time to respond me.

**Pull request closed without merging**
