### PR TITLE
recipes can create products

### PR DESCRIPTION
**Pull request by kriddles**
#374 
Initial work for self producing products.

A product can be assigned to a recipe. On recipe consumption the product is created using the price of the recipe along with desired servings.

An idea is perhaps on recipe consumption a checkbox could toggle the creation of the product?

### CODE REVIEW

**Comment by kriddles** [comment]
Also need to update the success toaster

**Comment by berrnd** [comment]
Cool, thanks for all your work! :)

Will have a detailed look later or tomorrow, but looks good so far I think.

> An idea is perhaps on recipe consumption a checkbox could toggle the creation of the product?

We already have a "do you really want"-popup when consuming a recipe, so maybe a button there to trigger the stock transaction. (?) Or maybe it's enough when the recipe has a product linked, when it has one, always book the transaction on consume...

And maybe a separate stock transaction type like `TRANSACTION_TYPE_SELF_PRODUCTION` would be good.

**Comment by kriddles** [comment]
Yeah I agree there should be a separate type.

**Comment by zebardy** [comment]
🧠💪👨‍💻🙌👍

**Comment by necr0dncr** [comment]
Hello! Hate to revive an older thread, but I was unsure if this should go here or be brought up as another potential feature.

I really love this aspect of the recipe and product management. But is there a way for the recipe to generate the product automatically?
As of right now I am assuming a product must be manually created, and then linked to the recipe with the "Produced Product".

**Comment by berrnd** [comment]
> Hate to revive an older thread

Hate that too, thanks for spamming ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)).

&nbsp;
> As of right now I am assuming a product must be manually created, and then linked to the recipe with the "Produced Product".

There are no hidden gems anywhere, so I don't see how that should be possible as of today.

**Pull request merged**
