### PR TITLE
Fix meal plan start page requirements

### PR DESCRIPTION
**Pull request by lwis**
I missed a requirement on my previous pull request, sorry.

### CODE REVIEW

**Comment by lwis** [comment]
If I enable the meal plan without enabling calendar, I didn't get the calendar functionality (I'd need to double check that, though). I thought the feature might be dependant?

**Comment by berrnd** [comment]
Not intentional, I will check that...

**Comment by berrnd** [comment]
So I think the only problem was that the menu entry in the sidebar was hidden when `FEATURE_FLAG_CALENDAR` was set to `false` (the meal plan is included in `FEATURE_FLAG_RECIPES`).

So should be fixed by https://github.com/grocy/grocy/commit/3328c789d41820edc1896312fdad4ebbbd1881f8.

Thanks for finding that! :)

**Comment by lwis** [comment]
Ah, np!

**Pull request closed without merging**
