### PR TITLE
389 Display ingredient amount as fractions

### PR DESCRIPTION
**Pull request by kriddles**
I was just playing around with a few of these functions found from https://stackoverflow.com/questions/59727517/how-to-convert-between-decimals-and-fractions-in-php

It did require me to enable php-gmp on my system to work.

I then played with an example in the views/recipes.blade.php changing the selectedRecipes Ingredients recipe_amount to instead be {{ decimalToFraction($selectedRecipePosition->recipe_amount) }}

In the demo this was now displayed 
/recipes?recipe=5

image

### CODE REVIEW

**Comment by kriddles** [comment]
This would allow the db to remain unchanged and continue to store as decimals.

A variable ?"displayAsFraction"? could be checked whether or not to display the decimalToFraction conversion for ingredients or even by product?

It would be nice to be able to add an ingredient to a recipe using a string such as "1/4" which would then fractionToDecimal to be stored in the db. This could be allowed if the variable "displayAsFraction" were at the product level?

**Comment by berrnd** [comment]
Cool, maybe it would work to only change how the number is displayed and keep decimal numbers internally. But let's test this first with a `1/3` amount - this is most of the time the problem which leads to that there is `0.00...01` of something left in stock at some point...

**Comment by kriddles** [comment]
I rewrote part of the decimalToFraction to better handle displaying 1/3 using a tolerance and precision.

I also have an example update to the consume so that a stock will be consumed if left with less than .01 remaining in the stock amount. Perhaps the .01 should be more? .0001?

**Comment by kriddles** [comment]
Using the DecimalToFraction function is relatively easy to show the user fractions, however I am not having much luck on adding to the RecipePosForm the ability to let the user input a fraction and then use the FractionToDecimal function to store the decimal value.

Is there an example somewhere of using the php functions in the js? Or how would you go about this?

**Comment by berrnd** [comment]
Thanks for trying this, I will have no time to look into this before sunday or so (but will push the new release tomorrow - seems to be everything new/included as of now is working... :)).

**Comment by kriddles** [comment]
No rush on it!

Thanks for getting a release ready

**Comment by kriddles** [comment]
This is rebased off of #556 so that the display as fractions can be included in the new recipes settings.

Currently this only allows switching to displaying the ingredient amount as fractions.

I have not attempted to allow the user to input as fractions. I would be ok with having a future enhancement to allow entering as fractions. 
I played around with eval() and it would seem to work to take the fraction string and convert to decimal. However right now entering as a fraction is not a big priority. There seem to be very few needs to enter 1/3 as an amount so most ingredient adds can be in decimal with viewing in fraction.

**Comment by berrnd** [comment]
> There seem to be very few needs to enter 1/3 as an amount so most ingredient adds can be in decimal with viewing in fraction.

Really? Sorry, still haven't tested it myself yet: But then I have to enter something like `0.33333` when I want to have `1/3`? I think also entering fractions would be needed, otherwise I don't know if anyone would find that that much useful...

So we need the convert functions on the frontend (JS) and also need to solve the input validation to only allow proper fractions...

**Comment by berrnd** [comment]
Closing this for now, I think that's far too outdated to be merged in that state in the meantime...

**Pull request closed without merging**
