### PR TITLE
Recipe updates

### PR DESCRIPTION
**Pull request by zsarnett**
- Update UI of Recipe Card
- Update UI of Gallery Cards
- Update logic for recipe creation - Only creates recipe once saved
- Update Recipe controller logic

### Before
image

### After
d886c07f3b5b09c8b97ccac509f76093
image

Fixes: #787

### CODE REVIEW

**Comment by zsarnett** [comment]
There is a lot here. a Lot to test. Sorry about that. Let me know if you have any questions.

**Comment by berrnd** [comment]
Wow, thanks again for all your work, looks amazing! 🤩

> Update logic for recipe creation - Only creates recipe once saved

The problem was that all was on one page so far, so including ingredients, and for adding/saving an ingredient a `recipe_id` was needed - but splitting the recipe "head" and ingredients creation should also work - will test it later...

**Comment by zsarnett** [comment]
Yea this way the system isn't prematurely creating a new Recipe. If I go to create a recipe and then end up forgetting something or now don't want to add it. I would just click back and would expect there not to be a new recipe created.

**Comment by vorkuta** [comment]
Nice one, thanks.

**Pull request merged**
