### PR TITLE
Implement async loading of products

### LINKED ISSUE #1808: Bug: Performance issues with large amount of products
Hello, first of all thanks to everyone involved for making such a useful ERP for home use.

I made a script to import the full stock list of a retail store chain using the API and this in itself works fine. However, now that I have ~4000 products in Grocy, the following issues become apparent:
- increased page load times (could be solved by not loading all product data on page load, but instead doing an API call when using typeahead inputs and when loading data for datatables, this also allows for implementing neccessary pagination for the datatables)
  - `/products`: 11.96s, 12.01s, 12.08s
  - `/purchase`: 2.98s, 3.00s, 3.70s
  - `/inventory`: 3.02s, 3.03s, 2.99s
- the typeahead function of [@danielfarrell/bootstrap-combobox](https://github.com/danielfarrell/bootstrap-combobox) is extremely slow with such a large amount of items, because it uses the CSS `display` property to show/hide 2-18 DOM elements for every row/product * ~4k products = ~8k-72k DOM elements every time it is opened/closed, requiring a full re-render of all elements by the browser. Modern solutions to this include pagination, infinite scrolling and windowing (windowing works best for this use case). None of these solutions are utilized by the plugin. It would be better to replace this plugin than to lodge an issue, as [the project is abandoned](https://github.com/danielfarrell/bootstrap-combobox/issues/250).
- interacting with the [datatables](https://github.com/DataTables/DataTables) plugin (sorting, hiding/showing groups, changing display settings) is extremely slow with such a large amount of items, but it has a solution to this which is not used by Grocy: pagination

`/consume` seems to be unaffected (735ms, 796 ms, 820 ms), probably because it does not have a typeahead input and as such does not load all products on page load. Though, as a result of this the input on the page requires exact product names or barcodes. Might open a separate issue for this, because typeahead functionality could still be useful (although hopefully with a new plugin, eventually).

Issue #848 seems to be related.

### PR DESCRIPTION
**Pull request by alexrsagen**
I made some changes in order to implement async loading of products in most places, this made everything load a lot faster whenever products were loaded on the page.
- products, productpicker, stockjournal, stockjournalsummary: converted from bootstrap-combobox to select2
- products: added server-side data loading to datatables, rewrote search to work server-side

Also made several improvements to the API:
- included related data on products directly in the response (and paved the way to do so on other data types as well)
- added a search option, which searches all fields on an object and some fields of related objects.
- added total and filtered row count to all API responses
- added support for collate nocase ordering via API
- added support for filtering any field on products relations (and paved the way to do so on other data types as well)

Added TODOs for all other selections and datatables with content provided by the server.

Pushing this as a draft PR, as I have not yet had the time to test this out thoroughly enough to call it ready for production use.

### CODE REVIEW

**Comment by berrnd** [comment]
Thanks a lot for your work and time you put into this!

However, would be great if you maybe can split this up into smaller parts, rewriting kind of the whole project at the end is kind of untestable and I will unlikely merge things like that.

Please also only put more time into such big changes if you also like to maintain them in the long term and test them thoroughly.

Just saying that, because we had something like that before (#1510 and other bigger PRs which turned out to break so much, not noticed at first).

> added total and filtered row count to all API responses

Please provide a use-case for what something is practically needed. I'm more than not a fan of adding theoretical stuff / headers because maybe that how x others do it.

**Review by berrnd — CHANGES_REQUESTED** [review]
After having a first quick look over the changes:

- Please try to adapt the existing code style and don't change just the style/tabs of not involved code parts (like line breaks after curly braces or tabs), this makes it really hard to see/compare what has really changed ([PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) is used, ref [.php-cs-fixer.php](https://github.com/grocy/grocy/blob/master/.php-cs-fixer.php) and also [.editorconfig](https://github.com/grocy/grocy/blob/master/.editorconfig))

- Please split the changes into smaller separate PRs as mentioned in my previous comment

**Comment by berrnd** [comment]
Quick speed comparison (same machine/browser/data; local development server; current Firefox Dev Edition; default demo data):

&nbsp;
**/products:**

Before: 
products_before
(All (26) products are shown at once.)

After / with this PR:
products_after
(Paging, only 10 products are shown at once.)

&nbsp;
**/purchase:**

Before:
purchase_before

After / with this PR:
purchase_after

So maybe more impressive when having more data, but at a first sight not so much by that...

**Comment by alexrsagen** [comment]
Thanks for the feedback.

> Please also only put more time into such big changes if you also like to maintain them in the long term and test them thoroughly.

Part of the reason this was published as a draft PR is to give myself time to use this, get feedback from you and ensure we don't break Grocy for other users. Definitely agree these changes should be tested thoroughly before merging anything.

> Please try to adapt the existing code style and don't change just the style of not involved code parts (like line breaks after curly braces or tabs)

I had some issues with the Laravel Blade auto-formatting. I tried several extensions, but could not find an extension that would not break anything. So for now, auto-formatting was disabled for some of these changes. If or when I split the changes up into smaller parts, I hope to be able to follow the project code formatting style.

Assuming you're also using VSCode, which extensions are you using to format Laravel Blade templates, PHP, CSS and JS? (I have an Intelephense license and use this, if that's worth mentioning).

> Please split the changes into smaller separate PRs as mentioned in my previous comment

No problem, can definitely do this, but it might take some time before I get it done.

**Comment by berrnd** [comment]
> Assuming you're also using VSCode, which extensions are you using to format Laravel Blade templates, PHP, CSS and JS?

See for example [there](https://github.com/grocy/grocy/issues/863#issuecomment-631298442) or here is my current actual list:
<details>
 <summary>code --list-extensions</summary>
<pre>
42Crunch.vscode-openapi
anseki.vscode-color
brapifra.phpserver
DavidAnson.vscode-markdownlint
DotJoshJohnson.xml
eamodio.gitlens
EditorConfig.EditorConfig
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
GitHub.vscode-pull-request-github
junstyle.php-cs-fixer
ms-vscode.powershell
onecentlin.laravel-blade
pflannery.vscode-versionlens
redhat.vscode-yaml
xdebug.php-debug
yzhang.markdown-all-in-one
Zignd.html-css-class-completion
zobo.php-intellisense
</pre>
</details>

About splitting this up, for me I see the API changes/extensions and then individual other changes based on that - so maybe
- API field search/filter enhancements
- API include related objects (JOIN)
- Select2 for productpicker
- DataTables stuff

For the API changes I would like to not introduce any breaking changes, there are a lot of apps and other integrations out in the wild, so only when really necessary. Also that could be merged first to be able to properly rebase the rest on that then.

**Comment by berrnd** [comment]
Looks outdated, so closing this - can be reopened anytime you like to continue on that.

**Pull request closed without merging**
