### PR TITLE
Fix grocy/grocy#834

### PR DESCRIPTION
**Pull request by teddybeermaniac**
Hi,
I tested a bit with data I entered into my instance and it looks, that with this change in `stock_missing_products_including_opened` view the missing amounts are calculated correctly, but
I installed grocy yesterday, so I'm not sure if I'm not misunderstanding how this feature should work.

Also I changed the comment for the `FEATURE_SETTING_STOCK_COUNT_OPENED_PRODUCTS_AGAINST_MINIMUM_STOCK_AMOUNT` option as only after seeing your [comment](https://github.com/grocy/grocy/issues/353#issuecomment-533203973) I got which value I want it to be set to.

Changes from previous migration containing this view:
```diff
 DROP VIEW stock_missing_products_including_opened;
 CREATE VIEW stock_missing_products_including_opened
 AS
 
 /* This is basically the same view as stock_missing_products, but the column "amount_missing" includes opened amounts */
 
 -- Products WITHOUT sub products where the amount of the sub products SHOULD NOT be cumulated
 SELECT
        p.id,
        MAX(p.name) AS name,
        p.min_stock_amount - (IFNULL(SUM(s.amount), 0) - IFNULL(SUM(s.amount_opened), 0)) AS amount_missing,
        CASE WHEN IFNULL(SUM(s.amount), 0) > 0 THEN 1 ELSE 0 END AS is_partly_in_stock
 FROM products_view p
 LEFT JOIN stock_current s
        ON p.id = s.product_id
 WHERE p.min_stock_amount != 0
        AND p.cumulate_min_stock_amount_of_sub_products = 0
        AND p.has_sub_products = 0
        AND p.parent_product_id IS NULL
 GROUP BY p.id
-HAVING IFNULL(SUM(s.amount), 0) < p.min_stock_amount
+HAVING IFNULL(SUM(s.amount), 0) - IFNULL(SUM(s.amount_opened), 0) < p.min_stock_amount
 
 UNION
 
 -- Parent products WITH sub products where the amount of the sub products SHOULD be cumulated
 SELECT
        p.id,
        MAX(p.name) AS name,
-       SUM(sub_p.min_stock_amount) - (IFNULL(SUM(s.amount_aggregated), 0) - IFNULL(SUM(s.amount_opened), 0)) AS amount_missing,
+       SUM(sub_p.min_stock_amount) - (IFNULL(SUM(s.amount_aggregated), 0) - IFNULL(SUM(s.amount_opened_aggregated), 0)) AS amount_missing,
        CASE WHEN IFNULL(SUM(s.amount), 0) > 0 THEN 1 ELSE 0 END AS is_partly_in_stock
 FROM products_view p
 JOIN products_resolved pr
        ON p.id = pr.parent_product_id
 JOIN products sub_p
        ON pr.sub_product_id = sub_p.id
 LEFT JOIN stock_current s
        ON pr.sub_product_id = s.product_id
 WHERE sub_p.min_stock_amount != 0
        AND p.cumulate_min_stock_amount_of_sub_products = 1
 GROUP BY p.id
-HAVING IFNULL(SUM(s.amount_aggregated), 0) < SUM(sub_p.min_stock_amount)
+HAVING IFNULL(SUM(s.amount_aggregated), 0) - IFNULL(SUM(s.amount_opened_aggregated), 0) < SUM(sub_p.min_stock_amount)
 
 UNION
 
 -- Sub products where the amount SHOULD NOT be cumulated into the parent product
 SELECT
        sub_p.id,
        MAX(sub_p.name) AS name,
        SUM(sub_p.min_stock_amount) - (IFNULL(SUM(s.amount), 0) - IFNULL(SUM(s.amount_opened), 0)) AS amount_missing,
        CASE WHEN IFNULL(SUM(s.amount), 0) > 0 THEN 1 ELSE 0 END AS is_partly_in_stock
 FROM products p
 JOIN products_resolved pr
        ON p.id = pr.parent_product_id
 JOIN products sub_p
        ON pr.sub_product_id = sub_p.id
 LEFT JOIN stock_current s
        ON pr.sub_product_id = s.product_id
 WHERE sub_p.min_stock_amount != 0
        AND p.cumulate_min_stock_amount_of_sub_products = 0
 GROUP BY sub_p.id
-HAVING IFNULL(SUM(s.amount), 0) < sub_p.min_stock_amount;
+HAVING IFNULL(SUM(s.amount), 0) - IFNULL(SUM(s.amount_opened), 0) < sub_p.min_stock_amount;
```

### CODE REVIEW

**Comment by gersilex** [comment]
Doing a functionality test right now.

**Comment by gersilex** [comment]
It seems to work as intended. Tried different actions and could not provoke a negative stock, underflows or other unwanted effects.

**Comment by berrnd** [comment]
Thanks for testing @gersilex! :)

**Comment by gersilex** [comment]
@berrnd Is there something we can do to be able to merge this?

**Comment by berrnd** [comment]
Still looks good, I just haven't had time to continue my work on grocy so far (see https://www.reddit.com/r/grocy/comments/hxeg31/when_can_we_expect_an_update/fz6apyt)...

If you want to have it now, just apply the migration (view change) manually, will not be a problem for normal upgrades.

**Review by berrnd — APPROVED** [review]

**Pull request merged**
