### PR TITLE
Locales: use http-accept-language or cookie

### LINKED ISSUE #934: Different language per user
_Originally requested in https://www.reddit.com/r/grocy/comments/hyryjx/one_install_multi_languages/_

Make it possible to set a different language per user.

### PR DESCRIPTION
**Pull request by fipwmaqzufheoxq92ebc**
Fixes #934 
I have added a new "LocaleMiddleware", which determines the Locale to use and sets a constant "GROCY_LOCALE".
It tries, in this order, until a valid locale is found:
1. Use a Cookie, I named it 'LOCALE', which can be set to the Locale-code, e.g. "en" or "de".
2. Use the Options of the HTTP-Header "Accept-Language"
3. Use the Setting GROCY_CULTURE

For 1, I planned to use the Locale-Picker of the public demos, but didn't find their source code.

The middleware is currently used only in production-mode.

Also note that user-inputs, e.g. products, aren't translated.

### CODE REVIEW

**Comment by berrnd** [comment]
Thank you, but do we really need this so "complex"?
I just thought about a new user setting for #934 (dropdown of all available language based on what's in the `localization` directory) which then sets `GROCY_CULTURE` accordingly...

> 2. Use the Options of the HTTP-Header "Accept-Language"

I for example prefer to use my browser in English, but other software (like grocy) in German, so that would never fit for me (just an example, probably it fits for most people...).

> For 1, I planned to use the Locale-Picker of the public demos, but didn't find their source code.

I don't think we need this so prominent in the header of each page.

I add all the "demo things" via [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself), can be seen when you check the source of the page, it's currently:

<details><summary>custom_css.html</summary><p>

```html
<link href="https://releases.grocy.info/demoresources/flag-icon-css/css/flag-icon.min.css?v=<?php echo $version ?>" rel="stylesheet">

<style>
	#demo-footer {
		color: #a7a7a7;
		font-size: 11px;
		font-family: sans-serif;
	}

	#demo-footer a {
		color: #7d7d7d;
		transition: all 0.3s;
	}

	#demo-footer a:hover {
		color: #337ab7;
		text-decoration: none;
		transition: all 0.3s;
	}

	#demo-footer a:focus {
		color: #ab2230;
		text-decoration: none;
		transition: all 0.3s;
	}
	
	.demo-footer-swagger-ui .col {
		width: 50%;
		margin: 0 auto;
	}
	
	.demo-footer-swagger-ui .text-center {
		text-align: center !important;
	}
	
	.legal-navigation {
		font-size: 10px;
	}

	.legal-navigation ul {
		list-style-type: none;
		margin: 0 0 0 0;
		padding-left: 0;
	}

	.legal-navigation li {
		display: inline;
	}

	.legal-navigation li:not(:first-child):before {
		content: ' | ';
	}

	.night-mode #demo-footer,
	body.night-mode {
		background-color: #333131;
	}
</style>
```

</p></details>

<details><summary>custom_js.html</summary><p>

```html
<script src="//kiwip.berrnd.org/js/ads/banner.js"></script>
<script type="text/javascript">
	var _paq = _paq || [];
	_paq.push(["setDomains", ["demo.grocy.info", "*.demo.grocy.info"]]);
	_paq.push(['trackPageView']);
	_paq.push(['enableLinkTracking']);
	_paq.push(['enableHeartBeatTimer', 10]);
	if (typeof window.PIWIK_NO_ADBLOCKER_RECOGNIZED == 'undefined') { _paq.push(['setCustomVariable', '1', 'Adblocker recognized', 'true']); } else { _paq.push(['setCustomVariable', '1', 'Adblocker recognized', 'false']); }
	(function() {
	var u="//kiwip.berrnd.org/";
	_paq.push(['setTrackerUrl', u+'js/']);
	_paq.push(['setSiteId', 15]);
	var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
	g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'js/'; s.parentNode.insertBefore(g,s);
	})();
</script>
<noscript><p><img src="//kiwip.berrnd.org/kiwip.php?idsite=15&rec=1" style="border:0;" alt=""></p></noscript>

<li id="demo-navbar-additions-left1" class="d-none nav-item dropdown mr-4">
	<a class="nav-link dropdown-toggle text-primary" href="#" data-toggle="dropdown"><i id="currentLanguageIcon" class="fas fa-language"></i> <span id="currentLanguage"></span></a>

	<div class="dropdown-menu">
		<a class="dropdown-item demo-language-change-link" href="https://cs.demo-prerelease.grocy.info" data-culture="cs"><i class="flag-icon flag-icon-cz"></i> <span id="txtcs"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://da.demo.grocy.info" data-culture="da"><i class="flag-icon flag-icon-dk"></i> <span id="txtda"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://de.demo.grocy.info" data-culture="de"><i class="flag-icon flag-icon-de"></i> <span id="txtde"></span></a>
		<!--<a class="dropdown-item demo-language-change-link" href="https://el.demo.grocy.info" data-culture="el_GR"><i class="flag-icon flag-icon-gr"></i> <span id="txtgr"></span></a>-->
		<a class="dropdown-item demo-language-change-link" href="https://en.demo.grocy.info" data-culture="en"><i class="fas flag-icon flag-icon-us"></i> <span id="txten"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://es.demo.grocy.info" data-culture="es"><i class="fas flag-icon flag-icon-es"></i> <span id="txtes"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://fr.demo.grocy.info" data-culture="fr"><i class="fas flag-icon flag-icon-fr"></i> <span id="txtfr"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://hu.demo.grocy.info" data-culture="hu"><i class="fas flag-icon flag-icon-hu"></i> <span id="txthu"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://it.demo.grocy.info" data-culture="it"><i class="fas flag-icon flag-icon-it"></i> <span id="txtit"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://ja.demo.grocy.info" data-culture="ja"><i class="fas flag-icon flag-icon-jp"></i> <span id="txtja"></span></a>
		<!--<a class="dropdown-item demo-language-change-link" href="https://ko.demo.grocy.info" data-culture="ko_KR"><i class="fas flag-icon flag-icon-kr"></i> <span id="txtko"></span></a>-->
		<a class="dropdown-item demo-language-change-link" href="https://nl.demo.grocy.info" data-culture="nl"><i class="fas flag-icon flag-icon-nl"></i> <span id="txtnl"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://no.demo.grocy.info" data-culture="no"><i class="fas flag-icon flag-icon-no"></i> <span id="txtno"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://pl.demo.grocy.info" data-culture="pl"><i class="fas flag-icon flag-icon-pl"></i> <span id="txtpl"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://pt-br.demo.grocy.info" data-culture="pt_BR"><i class="fas flag-icon flag-icon-br"></i> <span id="txtptbr"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://pt-pt.demo-prerelease.grocy.info" data-culture="pt_PT"><i class="fas flag-icon flag-icon-pt"></i> <span id="txtptpt"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://ru.demo.grocy.info" data-culture="ru"><i class="fas flag-icon flag-icon-ru"></i> <span id="txtru"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://sk.demo.grocy.info" data-culture="sk_SK"><i class="fas flag-icon flag-icon-sk"></i> <span id="txtsk"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://sv.demo.grocy.info" data-culture="sv_SE"><i class="fas flag-icon flag-icon-se"></i> <span id="txtsv"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://tr.demo.grocy.info" data-culture="tr"><i class="fas flag-icon flag-icon-tr"></i> <span id="txttr"></span></a>
		<a class="dropdown-item demo-language-change-link" href="https://zh-tw.demo.grocy.info" data-culture="zh_TW"><i class="fas flag-icon flag-icon-tw"></i> <span id="txttw"></span></a>
	</div>
</li>

<li id="demo-navbar-additions-left2" class="d-none nav-item dropdown">
	<a class="nav-link dropdown-toggle text-success" href="#" data-toggle="dropdown"><i class="fas fa-code-branch"></i> <span id="txtStableVersion"></span> <span class="small">(<span id="txtCurrentRelease" class="font-italic"></span>)</span></a>

	<div class="dropdown-menu">
		<a class="dropdown-item text-danger demo-branch-change-link" href="#" data-branch="preview"><i class="fas fa-code-branch"></i> <span id="txtPreviewVersion"></span> <span class="small">(<span id="txtNotYetReleased" class="font-italic"></span>)</span></a>
	</div>
</li>

<div id="demo-footer" class="row hide-when-embedded d-print-none d-none">
	<div class="col text-center pt-5 mt-5 pb-3">
		
		<div class="legal-navigation">
			<ul>
				<li>
					<a class="discrete-link" href="https://grocy.info/impressum">Impressum</a>
				</li>
				<li>
					<a class="discrete-link" href="https://grocy.info/datenschutz">Datenschutz</a>
				</li>
			</ul>
		</div>

		<div class="pt-3">
			grocy is a project by <a href="https://berrnd.de" target="_blank">Bernd Bestel</a>
			<br>
			Created with passion since 2017 and hosted on <a href="https://berrnd.net" target="_blank">berrnd.net</a> infrastructure
			<br>
			Life runs on code
		</div>

	</div>
</div>

<script>
	if (window.location.pathname == "/api")
	{
		// On the /api page jQuery is not available...
		document.getElementById("demo-footer").className += " demo-footer-swagger-ui";
		document.getElementById("demo-navbar-additions-left1").remove();
		document.getElementById("demo-navbar-additions-left2").remove();
	}
	else
	{
		if (GetUriParam("nodemoadditions") === undefined)
		{
			// Append demo navbar additions to the left side of the navbar
			var leftMostNavbarItem = $("#sidebarResponsive").find(".ml-auto");
			leftMostNavbarItem = leftMostNavbarItem.prepend($("#demo-navbar-additions-left1")[0].outerHTML.replace("d-none", ""));
			leftMostNavbarItem.prepend($("#demo-navbar-additions-left2")[0].outerHTML.replace("d-none", ""));
			
			// Add a demo info label next to the logo
			$(".navbar-brand").append('<span class="small ml-1"><span class="small text-muted font-italic"><span id="txtDemo"></span></span></span>');
			
			// Hide the current language from the demo language change menu
			$(".demo-language-change-link[data-culture='" + Grocy.Culture + "']").addClass("d-none");
			
			// Append the footer to the page content section
			$("#page-content").append($("#demo-footer")[0].outerHTML.replace("d-none", ""));
			
			// Set the demo version branch change link to point to the same language of the other branch
			var otherBranchSameLanguageLink = $(".demo-language-change-link[data-culture='" + Grocy.Culture + "']").attr("href").replace("demo.grocy.info", "demo-prerelease.grocy.info");
			$(".demo-branch-change-link").attr("href", otherBranchSameLanguageLink);

			// Translate texts
			$("#txtcs").text(__t("Czech"));
			$("#txtda").text(__t("Danish"));
			$("#txtde").text(__t("German"));
			$("#txtgr").text(__t("Greek"));
			$("#txten").text(__t("English"));
			$("#txtes").text(__t("Spanish"));
			$("#txtfr").text(__t("French"));
			$("#txthu").text(__t("Hungarian"));
			$("#txtit").text(__t("Italian"));
			$("#txtja").text(__t("Japanese"));
			$("#txtko").text(__t("Korean"));
			$("#txtnl").text(__t("Dutch"));
			$("#txtno").text(__t("Norwegian"));
			$("#txtpl").text(__t("Polish"));
			$("#txtptbr").text(__t("Portuguese (Brazil)"));
			$("#txtptpt").text(__t("Portuguese (Portugal)"));
			$("#txtru").text(__t("Russian"));
			$("#txtsk").text(__t("Slovak"));
			$("#txtsv").text(__t("Swedish"));
			$("#txttr").text(__t("Turkish"));
			$("#txttw").text(__t("Chinese (Taiwan)"));
			$("#txtDemo").text(__t("Demo"));
			$("#txtStableVersion").text(__t("Stable version"));
			$("#txtPreviewVersion").text(__t("Preview version"));
			$("#txtCurrentRelease").text(__t("current release"));
			$("#txtNotYetReleased").text(__t("not yet released"));
			
			// Set the text and icon of the demo language change menu dropdown to the current language
			$("#currentLanguage").text($(".demo-language-change-link[data-culture='" + Grocy.Culture + "']").text());
			$("#currentLanguageIcon").attr("class", $(".demo-language-change-link[data-culture='" + Grocy.Culture + "']").find("i").attr("class"));
		}
	}
	
	$(".demo-language-change-link").on("click", function(e)
	{
		var destinationLanguage = $(e.currentTarget).attr("data-culture");

		var piwikTracker = Piwik.getAsyncTracker();
		piwikTracker.trackEvent("Demo instances", "Switched language", destinationLanguage);
	});
	
	$(".demo-branch-change-link").on("click", function(e)
	{
		var destinationBranch = $(e.currentTarget).attr("data-branch");

		var piwikTracker = Piwik.getAsyncTracker();
		piwikTracker.trackEvent("Demo instances", "Switched branch", destinationBranch);
	});
	
	$(document).on("click", "#barcodescanner-start-button", function(e)
	{
		var piwikTracker = Piwik.getAsyncTracker();
		piwikTracker.trackEvent("User insights", "Started camera barcode scan");
	});
</script>
```

</p></details>

**Comment by fipwmaqzufheoxq92ebc** [comment]
> I for example prefer to use my browser in English, but other software (like grocy) in German, so that would never fit for me (just an example, probably it fits for most people...).

For that case you can use Option 1.
That's why there is this ordering: 
1. If the user set a preference, use it.
2. If the user has no preference, use the browser language.
3. Fallback to GROCY_CULTURE

1 is implemented via cookie, as it was easier to implement. (But we could instead use user-settings.)

I think 2 is what most users would use.

We could also introduce a new Setting, which disables "multi-language-mode" (and always uses GROCY_CULTURE).

> I don't think we need this so prominent in the header of each page.
> I add all the "demo things" via custom JS, can be seen when you check the source of the page, it's currently:

**Comment by berrnd** [comment]
Ok, then let's add it like you proposed.

Some thoughts:
- Drop `GROCY_CULTURE`, rename to `GROCY_DEFAULT_LOCALE` and is it as the fallback
- A user setting would be better I would say, as only this would be persistent for each user when using different browsers (new settings page, as we currently have no generic user settings so far)

> We could also introduce a new Setting, which disables "multi-language-mode" (and always uses GROCY_CULTURE).

Not needed, I think, when the default language setting is used as long as the user has not defined a own one.

**Comment by fipwmaqzufheoxq92ebc** [comment]
> Ok, then let's add it like you proposed.
> 
> Some thoughts:
> 
>     * Drop `GROCY_CULTURE`, rename to `GROCY_DEFAULT_LOCALE` and use this as the fallback
> 
>     * A user setting would be better I would say, as only this would be persistent for each user when using different browsers (new settings page, as we currently have no generic user settings so far)

Done.

While implementing, I needed to reorder the middlewares, as LocaleMiddleware needs to run after AuthMiddleware (to access GROCY_USER_ID to get the setting):
That causes that CORS-preflight-OPTIONS now requires authentication.
And I apply CORS-Middleware to all views, even when authentication fails, which should fix #861 .

**Comment by berrnd** [comment]
Cool, thanks - will test it later. :)

> That causes that CORS-preflight-OPTIONS now requires authentication.

Needs also to be tested, I think those CORS OPTIONS requests require to be without authentication.

**Comment by fipwmaqzufheoxq92ebc** [comment]
> Needs also to be tested, I think those CORS OPTIONS requests require to be without authentication.

You're right - I fixed that, OPTIONS now always return successfully.

**Review by berrnd — APPROVED** [review]

**Pull request merged**
