### PR TITLE
Adding the barcode scanning script

### PR DESCRIPTION
**Pull request by TheFuzz4**
So you inspired me to enhance what little I did know about python.  I wrote this script for adding new items to the system.  Increasing the quantity as well as decreasing. 
The script requires the user to print off a barcode (or use some barcode from something else) to setup as the ADD_ID.  When this is scanned it will put the script into add mode and start increasing.  Scan that code again and it shifts back to consume mode.  Out of the box this runs in consume mode.  I just bought a cheap scanner and plugged the USB dongle into one of the pi's in my house and just run the script locally there.  Right now I run the script in a screen session since I don't have any logging setup in the script.

I am by no means a developer and I am sure there are areas of my script that can use some enhancements or maybe some better logic.  I optimized it to the best of my abilities for the moment and I'm sure I'll have further enhancements with it.  But hey it gets the job done.  Your API is great and without it this would be a lot harder to accomplish.  I hope that this helps people.  

If there is a DB that you don't want it to search externally just set the token to empty and it will skip on over it.  

I have issues with rapid scanning, my scanner starts to report in only pieces of the UPC so I have to give it a few second pause between scans but only when its something that isn't in the system already.  If its local the script fires off really fast. 

Well let me know what you think about this and I'll continue to do my part to help contribute to the project.

### CODE REVIEW

**Comment by berrnd** [comment]
Thanks! :)

Great idea, already also thought about a "scan mode" in the UI which does also this - removing or adding just one item per scanned barcode.

The only problem I see about this approach is that you don't get feedback when something has not worked. My initial idea was to provide maybe audio feedback, to still be able to scan "blindly" anyway, without having to look always on the screen.

So I don't know if it's the best place to just include the script here, maybe a separate repository "grocy-tools" or something fits better, or even a standalone repository just for this, because it would also need a bit of explanation how to use it and maybe there will be also issues/discussuions when somebody get to use it - so if you want, we would just need a repo name and I will set it up, give you write access and you can add/maintain everything there... (?)

**Comment by berrnd** [comment]
> we would just need a repo name and I will set it up

What about "grocy-pyscanner"?

**Comment by TheFuzz4** [comment]
That sounds great to me.  Yeah I've been trying to figure out some method
of giving you feedback.  Best idea I have right now is to have my script
call my home assistant via API and give feedback that route.  Still
thinking.  But yeah that repo name works for me.  Thank you for your
feedback.

Jason

**Comment by berrnd** [comment]
Great, I created the repository and added you with write permissions:

https://github.com/grocy/grocy-pyscanner

Feel free to add there anything you want to make this a great little helper tool. :)
Of course we can then also add a hint on the main repos README and on the homepage...

So closing this here for now.

**Comment by TheFuzz4** [comment]
Thank you I will do just that.

**Comment by TheFuzz4** [comment]
Its saying that I don't have permissions to do a push to the repo

**Comment by berrnd** [comment]
Seems that you don't have accepted the invitation yet - should be visible for you under https://github.com/grocy/grocy-pyscanner/invitations and for the org here: https://github.com/grocy

**Comment by TheFuzz4** [comment]
Thanks that did it

**Pull request closed without merging**
