### PR TITLE
Add user-field-type "file"

### PR DESCRIPTION
**Pull request by fipwmaqzufheoxq92ebc**
I added a new userfield-type "file", which allows to add a file to an object.
Files are uploaded via FilesApiController and shown as a link in tables.
I also added a new non-api-route to view the file, to show a human readable name, and to get a "normal" error page (instead of JSON).

Related to #262 and #441

### CODE REVIEW

**Comment by berrnd** [comment]
Should also fit for #282, just that the uploaded file shold be checked to be a picture and then also rendered as one (size?).

**Comment by fipwmaqzufheoxq92ebc** [comment]
> Should also fit for #282, just that the uploaded file shold be checked to be a picture and then also rendered as one (size?).

I implemented a new field type "image", which is always served with force_serve_type=picture.
For tables I use a default size of 32x32 which is small, but there is not much space.

**Review by berrnd — APPROVED** [review]
Works in my tests, thanks! :)

I just added to render files and images in dialogs, when clicked on them in tables.

Also noted that empty userfields are never deleted from the `userfield_values` tables and that caused warnings as an empty file name was used on the pages - just added triggers to prevent empty fields in general.

**Comment by berrnd** [comment]
I created a follow-up issue (#978) to fulfill #262 and #441 even better specifically for Equipment.

**Pull request merged**
