### PR TITLE
Feature request : api/stock can return detailed products #487

### LINKED ISSUE #487: Feature request : api/stock can return detailed products
Hi :)

Can you add an argument to api/stock to get products with details ?
To avoid running api/product/{product_id} on every products.

Please :)

### PR DESCRIPTION
**Pull request by gsacre**
The response of the call '/api/stock' now returns a new attribute
('product') which contains the details of the related product.

Created new pull request after discussion with previous PR to keep things clean.

Closes #487.

### CODE REVIEW

**Comment by berrnd** [comment]
Thank you, works perfectly, but I tried to simplify it a little bit, see https://github.com/grocy/grocy/commit/d0036e8034fd3daf208894bfde5151e786250a73.

https://github.com/grocy/grocy/blob/d0036e8034fd3daf208894bfde5151e786250a73/services/StockService.php#L29-L38

**Comment by gsacre** [comment]
Thank you!

Just for my understanding, and as I'm not that familiar with this framework, don't you execute twice the $sql query on the stock_current table (lines 29 and 31)?

I'm asking also so that I can better help next time :-)

**Comment by berrnd** [comment]
Line 31 queries all products which are part of the query before by using it as a subquery (so yes, it's executed twice) - just thought that it's cheaper to do it that way as one foreach-loop less is necassary, but haven't measured it...

`$this->Database` is an instance of the used ORM LessQL, see here :https://github.com/morris/lessql/blob/master/doc/api.md

So `$this->Database->products()` is basically the query `SELECT * FROM products`....

**Comment by gsacre** [comment]
Thanks for the explanation!

**Pull request merged**
