### PR TITLE
product in mealplan

### PR DESCRIPTION
**Pull request by kriddles**
#450 

Now that recipes can create products then adding products to meal plans will be useful and would be nice to have for the release.

This is a work in progress commit not quite up to master just to show the work if you want to take it a bit further. It's almost there.

It may be useful to add a new product db column called ?"include_in_mealplan"? that way products can be limited in the mealplan dropdown. This would be a checkbox option on the product creation/edit pages.

### CODE REVIEW

**Comment by berrnd** [comment]
Haven't thought about this in detail, but as the meal plan is based on (internal) nested recipes (per day and week), it should be only necessary to include the product in the day recipe (maybe also the week recipe, don't know right now if the week recipe is just a recipe which includes all day recipes)...

Also the `recipe_id` column of the `meal_plan` table does not allow `NULL` values currently, need to be changed then, but also need to be checked that then either `recipe_id` or `product_id` is set...

Or maybe just create a new (internal) recipe (same name as the product, at least for displaying) for those case and don't change anything else (maybe easier)...

**Comment by kriddles** [comment]
Definitely do not merge this at the moment; it's still set up just for dev since I updated an earlier migration. Just a little more tinkering on it.

I removed the constraints on the meal plan table however it looks like in order to actually remove them we'll have to create a new table, copy the data over, delete the original, rename the new table.

**Comment by berrnd** [comment]
> I removed the constraints on the meal plan table however it looks like in order to actually remove them we'll have to create a new table, copy the data over, delete the original, rename the new table.

Yes, that's unfortunately the only way in SQLite as altering or removing columns is not possible...

See for example [this migration](https://github.com/grocy/grocy/blob/dfc05e0bec2c524dc2f35a833f8fff6435f63a46/migrations/0048.sql) where the `shopping_list` table was "edited".
Important is also `PRAGMA legacy_alter_table`, as since a maybe two year old version of SQLite all references of a table (in views and triggers) get renamed when renaming a table...

**Comment by berrnd** [comment]
I made some changes for #477 which also may help here:
- The `meal_plan` table now has a column `type` (currently to distinguish between recipes and notes, can also be used for products)
- The `recipe_id` column is not longer a `NOT NULL` column

**Comment by kriddles** [comment]
I updated my work in progress for allowing products for meal plans based on your changes that helped.

Take a look when you get a moment. I won't be able to take it much further this weekend.
It currently allows adding a product to the meal plan, deleting the product once added, and consuming the product with Undo working.

My last commit attempts to clear the product or recipe picker but for some reason it is not actually clearing the values so both product_id and recipe_id are being set in the database? This will cause an error on the page. An error will not occur if you open the modal and only select a product and save.

**Comment by berrnd** [comment]
I will have a look, but maybe just a separate modal would be easier, like now for the note a new link in the "add button dropdown"...

**Comment by kriddles** [comment]
That sounds great and much simpler

**Comment by berrnd** [comment]
I finished this now in https://github.com/grocy/grocy/commit/e111d07f4e381ec064abb19b5e227c0efdd99a19.

**Pull request closed without merging**
